# Generated by Django 6.0.5 on 2026-05-31 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoal',
            options={'verbose_name': 'Perfil Pessoal', 'verbose_name_plural': 'Perfis Pessoais'},
        ),
        migrations.AddField(
            model_name='pessoal',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='git',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='linked',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='url_imagem',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
